#version 450

#extension GL_EXT_control_flow_attributes : enable
#extension GL_EXT_shader_16bit_storage : require

#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require

#extension GL_KHR_cooperative_matrix : enable
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_KHR_shader_subgroup_basic : enable

#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int32 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_EXT_shader_16bit_storage : require

#extension GL_QCOM_cooperative_matrix_conversion : enable
//#extension GL_EXT_debug_printf : enable

struct block_q4_0 {
    float16_t d;
    uint8_t qs[16];
};
struct block_q4_0_packed16 {
    float16_t d;
    uint16_t qs[16 / 2];
};

layout(local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0) readonly  buffer A { block_q4_0 data_a[]; };
layout(binding = 0) readonly  buffer A_PACKED16 { block_q4_0_packed16 data_a_packed16[]; };
//layout(binding = 1) readonly  buffer B { mat2x4 data_b[];}; // Not used here
layout(binding = 1) readonly  buffer Bf { float  data_bf[]; };
layout(binding = 2) writeonly buffer D { float data_d[]; };

layout(push_constant) uniform parameter
{
    uint M;
    uint N;
    uint K;
    uint stride_a;
    uint stride_b;
    uint stride_d;

    uint batch_stride_a;
    uint batch_stride_b;
    uint batch_stride_d;

    uint base_work_group_z;
    uint num_batches;
    uint k_split;
    uint ne02;
    uint ne12;
    uint broadcast2;
    uint broadcast3;
} p;

layout(constant_id = 0) const uint BLOCK_SIZE = 64;
layout(constant_id = 1) const uint BM = 64;
layout(constant_id = 2) const uint BN = 64;
layout(constant_id = 3) const uint BK = 16;
layout(constant_id = 4) const uint WM = 32;
layout(constant_id = 5) const uint WN = 32;
layout(constant_id = 6) const uint WMITER = 2;
layout(constant_id = 7) const uint TM = 64;
layout(constant_id = 8) const uint TN = 64;
layout(constant_id = 9) const uint TK = 16;
layout(constant_id = 10) const uint WARP = 32;

//#define K_TILE_FIRST  // New code: K-tiled first support
#define tileK 16 //  unsigned int tileK = (8 * 4) / sizeof(T); // tileK=8 for FP32, 16 for FP16, 32 for INT8

void main() {
    //bool print = (gl_GlobalInvocationID.x == 0 && gl_GlobalInvocationID.y == 0 && gl_GlobalInvocationID.z == 0);

//  const uint batch_idx = gl_WorkGroupID.z + p.base_work_group_z;
    const uint batch_idx = gl_GlobalInvocationID.z;

    const uint i13 = batch_idx / p.ne12;
    const uint i12 = batch_idx % p.ne12;

    const uint i03 = i13 / p.broadcast3;
    const uint i02 = i12 / p.broadcast2;

    const uint batch_idx_a = i03 * p.ne02 + i02;

    const uint blocks_m = (p.M + BM - 1) / BM;
    const uint ir = gl_WorkGroupID.x % blocks_m;
    const uint ik = gl_WorkGroupID.x / blocks_m;
    const uint ic = gl_WorkGroupID.y;

    const uint warp_r = gl_SubgroupID % (BM / TM);
    const uint warp_c = gl_SubgroupID / (BM / TM);

    const uint start_k = ik * p.k_split;
    const uint end_k = min(p.K, (ik + 1) * p.k_split);

    uint pos_a = (batch_idx_a * p.batch_stride_a + ir * BM * p.stride_a + (warp_r * TM) * p.stride_a + start_k);

#if defined(K_TILE_FIRST)  // New code: K-tiled first support
    uint pos_b = (batch_idx * p.batch_stride_b + (warp_c * TN) * p.stride_b + start_k);
    uint local_stride_b = gl_SubgroupInvocationID * tileK;
#else
    uint pos_b = (batch_idx * p.batch_stride_b + ic * BN * p.stride_b + (warp_c * TN) * p.stride_b + start_k);
    uint local_stride_b = gl_SubgroupInvocationID * p.stride_b;
#endif

    coopmat < float16_t, gl_ScopeSubgroup, TM, TK, gl_MatrixUseA > matA;
    coopmat < float16_t, gl_ScopeSubgroup, TK, TN, gl_MatrixUseB > matB;
    coopmat < float16_t, gl_ScopeSubgroup, TM, TN, gl_MatrixUseAccumulator > matC;

    matC = coopmat < float16_t, gl_ScopeSubgroup, TM, TN, gl_MatrixUseAccumulator >(0.0f);
    float16_t vecAh_block[BK];
    float16_t vecBh[TK];
    uint vui[4];
    float16_t d;
    float16_t vecAh[TK];
    float16_t vecCh[TN];

    for (uint block = start_k; block < end_k; block += TK) 
    {
#if defined(K_TILE_FIRST)  // New code: K-tiled first support
        uint base_b = pos_b + (ic * BN) * tileK;
#else
        // Old code: linear mapping, K first
        uint base_b = pos_b;
#endif
        [[unroll]] for (int k = 0; k < 16; k++)
            vecBh[k] = float16_t(data_bf[base_b + local_stride_b + k]);

        if (block % BK == 0)
        {
            const uint ib = pos_a / 32 + gl_SubgroupInvocationID * p.stride_a / 32;
            d = data_a_packed16[ib].d;
            [[unroll]] for (uint i = 0; i < 4; i++)
            {
                vui[i] = uint(data_a_packed16[ib].qs[2 * i]) | (uint(data_a_packed16[ib].qs[2 * i + 1]) << 16);
                const f16vec4 v0 = (f16vec4(unpack8((vui[i] >> 0) & 0x0F0F0F0F)) - float16_t(8.0f)) * d;
                const f16vec4 v1 = (f16vec4(unpack8((vui[i] >> 4) & 0x0F0F0F0F)) - float16_t(8.0f)) * d;
                vecAh_block[4 * i + 0] = float16_t(v0.x);
                vecAh_block[4 * i + 1] = float16_t(v0.y);
                vecAh_block[4 * i + 2] = float16_t(v0.z);
                vecAh_block[4 * i + 3] = float16_t(v0.w);
                vecAh_block[4 * i + 16] = float16_t(v1.x);
                vecAh_block[4 * i + 17] = float16_t(v1.y);
                vecAh_block[4 * i + 18] = float16_t(v1.z);
                vecAh_block[4 * i + 19] = float16_t(v1.w);
            }
        }

        if (block % BK == 0)
            extractSubArrayQCOM(vecAh_block, 0, vecAh);
        else
            extractSubArrayQCOM(vecAh_block, 16, vecAh);
        //extractSubArrayQCOM(vecAh_block, block%BK, vecAh);  // compiler has an issue realizing this is a constant

#ifndef XPOSE
        vectorToCoopmatQCOM(vecAh, matA);
        vectorToCoopmatQCOM(vecBh, matB);
#else
        vectorToCoopmatQCOM(vecAh, matB);
        vectorToCoopmatQCOM(vecBh, matA);
#endif

        matC = coopMatMulAdd(matA, matB, matC);

        pos_a += TK;
	
#if defined(K_TILE_FIRST) // New code: K-tiled first support
        pos_b += TK * p.N;
#else
        pos_b += TK;
#endif	
    }

    const uint store_r = gl_SubgroupInvocationID % TM;

    const uint dr = ir * BM + warp_r * TM;
    const uint dc = ic * BN + warp_c * TN;
    
//  const uint offsets = batch_idx * p.batch_stride_d + ik * p.batch_stride_d * p.num_batches;
    const uint offsets = batch_idx * p.batch_stride_d + ik * p.batch_stride_d * gl_NumWorkGroups.z;
    const bool is_aligned = p.stride_d % 4 == 0;
    const bool is_in_bounds = dr + TM <= p.M && dc + TN <= p.N;

    if (is_aligned && is_in_bounds) {
        coopmat < float, gl_ScopeSubgroup, TM, TN, gl_MatrixUseAccumulator > cm_dtype = coopmat < float, gl_ScopeSubgroup, TM, TN, gl_MatrixUseAccumulator >(matC);
#ifndef XPOSE
        coopMatStore(cm_dtype, data_d, offsets + dc * p.stride_d + dr, p.stride_d, gl_CooperativeMatrixLayoutColumnMajor);
#else
        coopMatStore(cm_dtype, data_d, offsets + dc * p.stride_d + dr, p.stride_d, gl_CooperativeMatrixLayoutRowMajor);
#endif
    } else if (is_in_bounds) {
#ifndef XPOSE
        coopmatToVectorQCOM(matC, vecCh);
        [[unroll]] for (uint col = 0; col < TN; col++)
            data_d[offsets + (dc + col) * p.stride_d + dr + store_r] = float(vecCh[col]);
#else
        coopmatToVectorQCOM(matC, vecCh);
        [[unroll]] for (uint col = 0; col < TN; col++)
            data_d[offsets + (dc + store_r) * p.stride_d + dr + col] = float(vecCh[col]);
#endif
    } else if (dr < p.M && dc < p.N) {
#ifndef XPOSE
        coopmatToVectorQCOM(matC, vecCh);
        [[unroll]] for (uint col = 0; col < TN; col++)
            if (dr + store_r < p.M && dc + col < p.N)
                data_d[offsets + (dc + col) * p.stride_d + dr + store_r] = float(vecCh[col]);
#else
        coopmatToVectorQCOM(matC, vecCh);
        [[unroll]] for (uint col = 0; col < TN; col++)
            if (dr + col < p.M && dc + store_r < p.N)
                data_d[offsets + (dc + store_r) * p.stride_d + dr + col] = float(vecCh[col]);
#endif
    }
}