#version 450
#extension GL_GOOGLE_include_directive : enable

#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int32 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_KHR_shader_subgroup_basic : enable


uint32_t fp32_to_bf16(float f) {
    uint32_t u = floatBitsToUint(f);
    u = (u + (0x7fff + ((u >> 16) & 1))) >> 16;
    return u;
}

float bf16_to_fp32(uint32_t u) {
    return uintBitsToFloat(u << 16);
}

#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_control_flow_attributes : require

layout(push_constant) uniform parameter
{
    uint ne;
    uint ne00;
    uint ne01;
    uint ne02;
    uint ne03;
    uint nb00;
    uint nb01;
    uint nb02;
    uint nb03;
    uint ne10;
    uint ne11;
    uint ne12;
    uint ne13;
    uint nb10;
    uint nb11;
    uint nb12;
    uint nb13;
    uint ne20;
    uint ne21;
    uint ne22;
    uint ne23;
    uint nb20;
    uint nb21;
    uint nb22;
    uint nb23;
    uint misalign_offsets;
    float param1; // not use here
    float param2; // not use here
    int param3;   // not use here
}p;

layout(binding = 0) readonly buffer  A { float data_a[]; };
layout(binding = 1) readonly buffer  B { float data_b[]; };
layout(binding = 2) writeonly buffer D { float data_d[]; };

layout(constant_id = 0) const bool norepeat = false;

uint get_idx() {
    return gl_GlobalInvocationID.z * 262144 + gl_GlobalInvocationID.y * 512 + gl_GlobalInvocationID.x;
}

uint get_aoffset() { return p.misalign_offsets >> 16; }
uint get_boffset() { return (p.misalign_offsets >> 8) & 0xFF; }
uint get_doffset() { return p.misalign_offsets & 0xFF; }

uint fastmod(uint a, uint b) {
    if ((b & (b - 1)) == 0) {
        return a & (b - 1);
    }
    return a % b;
}

uint fastdiv(uint a, uint b) {
    return (a < b) ? 0 : (a / b);
}

void get_indices(uint idx, out uint i00, out uint i01, out uint i02, out uint i03) {
    i03 = fastdiv(idx, (p.ne02 * p.ne01 * p.ne00));
    const uint i03_offset = i03 * p.ne02 * p.ne01 * p.ne00;
    i02 = fastdiv((idx - i03_offset), (p.ne01 * p.ne00));
    const uint i02_offset = i02 * p.ne01 * p.ne00;
    i01 = (idx - i03_offset - i02_offset) / p.ne00;
    i00 = idx - i03_offset - i02_offset - i01 * p.ne00;
}

uint src0_idx(uint i00, uint i01, uint i02, uint i03) {
    return i03 * p.nb03 + i02 * p.nb02 + i01 * p.nb01 + i00 * p.nb00;
}

uint src1_idx(uint i00, uint i01, uint i02, uint i03) {
    if (norepeat) {
        return i03 * p.nb13 + i02 * p.nb12 + i01 * p.nb11 + i00 * p.nb10;
    }
    else {
        return fastmod(i03, p.ne13) * p.nb13 + fastmod(i02, p.ne12) * p.nb12 + fastmod(i01, p.ne11) * p.nb11 + fastmod(i00, p.ne10) * p.nb10;
    }
}

uint dst_idx(uint i00, uint i01, uint i02, uint i03) {
    return i03 * p.nb23 + i02 * p.nb22 + i01 * p.nb21 + i00 * p.nb20;
}

const uint num_threads = 256;

layout(local_size_x = num_threads, local_size_y = 1, local_size_z = 1) in;

void main() {
    uint idx = get_idx();

    const uint num_iter = 2;

    [[unroll]] for (uint i = 0; i < num_iter; ++i) {
        if (idx >= p.ne) {
            continue;
        }
        uint i00, i01, i02, i03;
        get_indices(idx, i00, i01, i02, i03);

        //data_d[get_doffset() + dst_idx(i00, i01, i02, i03)] = float(float(data_a[get_aoffset() + src0_idx(i00, i01, i02, i03)]) * float(data_b[get_boffset() + src1_idx(i00, i01, i02, i03)]));
        uint idx_in = get_doffset() + dst_idx(i00, i01, i02, i03);
        uint data_a_off = get_aoffset() + src0_idx(i00, i01, i02, i03);
        uint data_b_off = get_boffset() + src1_idx(i00, i01, i02, i03);
        float a = data_a[data_a_off];
        float b = data_b[data_b_off];
        float d = a * b;

        // Assuming k % tileK == 0
        const uint tileK = 16;
        uint k = p.ne00;
        uint m_or_n = p.ne01;
        uint row_in = idx_in / k;            // mul_f32_f32_f32: uint k = p.ne00;
        uint col_in = (idx_in % k) / tileK;
        uint kk = idx_in % tileK;
        uint idx_out = tileK * (col_in * m_or_n + row_in) + kk; // mul_f32_f32_f32: uint m_or_n = p.ne01;

        data_d[idx_out] = d;

        idx += num_threads;
    }
}


